baseURL = 'https://kadima.cloud/'
languageCode = 'en-us'
title = 'Kadima Cloud'
theme = "kadima"

[permalinks]
  post = "/:title/"

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  page = ["HTML"]
  taxonomy = ["HTML"]
  taxonomyTerm = ["HTML"]

[outputFormats]
  [outputFormats.HTML]
    mediaType = "text/html"
    baseName = "index"
